### ISSUE TITLE
No pastebin link 3:

### ISSUE THREAD

**Issue by PGtheVRguy** [MCJack123/CC-Archive#2]
I found this really useful and want to use this in a project, but there is no easy way to install this for most users without a quick pastebin link for tools like tar.lua and I dont want to redistribute it amongst my software without permission.

**Comment by MCJack123** [comment]
1. Use `wget https://raw.githubusercontent.com/MCJack123/CC-Archive/master/file.lua`.
2. All files are licensed for redistribution following various terms. See the readme for more information on the license for each file.
3. These programs haven't been updated in a long time and may be broken/bad code. Use at your own risk.
